### PR TITLE
Pedro tests changing branch on local repository

### PR DESCRIPTION
**Pull request by ppereiraKTH**
Just testing pulling, by Pedro.

### CODE REVIEW

**Comment by adaldo** [comment]
There is no conflict though. Is that all right?

**Comment by ppereiraKTH** [comment]
No conflict. But do not accept it just yet.

I want to see if when I perform a change, the change is incorporated in the new pull request.

**Comment by ppereiraKTH** [comment]
Antonio, can you deny my pull request?

**Comment by adaldo** [comment]
You closed it before I could deny it :(

**Comment by ppereiraKTH** [comment]
Sorry! :P

**Pull request closed without merging**
